runtime: python312
instance_class: F4_1G
automatic_scaling:
  min_instances: 0
  max_instances: 3

entrypoint: gunicorn --workers=1 --threads=8 --timeout=0 -b :$PORT backend.app:app

handlers:

- url: /static
  static_dir: frontend/static

- url: /.*
  script: auto
  secure: always # Redirige todo a HTTPS
