runtime: python312
instance_class: F4_1G
automatic_scaling:
  min_instances: 0
  max_instances: 3

entrypoint: gunicorn --workers=1 --threads=8 --timeout=0 -b :$PORT app:app

handlers:

- url: /static
    static_dir: frontend/static

- url: /.*
    script: backend/app.py
    secure: always
